# Generated by Django 3.0.7 on 2020-07-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed', models.BooleanField()),
                ('timestamp_mapped', models.DateTimeField(auto_now=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('iri', models.URLField(blank=True, null=True, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CURRENT', 'current'), ('OBSOLETE', 'obsolete'), ('DELETED', 'deleted'), ('NEEDS_IMPORT', 'needs_import'), ('AWAITING_IMPORT', 'awaiting_import'), ('NEEDS_CREATION', 'needs_creation'), ('AWAITING_CREATION', 'awaiting_creation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('cross_refs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CURRENT', 'current'), ('UNMAPPED', 'unmapped'), ('OBSOLETE', 'obsolete'), ('DELETED', 'deleted'), ('NEEDS_IMPORT', 'needs_import'), ('AWAITING_IMPORT', 'awaiting_import'), ('NEEDS_CREATION', 'needs_creation'), ('AWAITING_CREATION', 'awaiting_creation'), ('AWAITING_REVIEW', 'awaiting_review')], max_length=50)),
                ('number_of_source_records', models.IntegerField(blank=True, null=True)),
                ('timestamp_added', models.DateTimeField(auto_now=True)),
                ('timestamp_updated', models.DateTimeField(auto_now_add=True)),
                ('current_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Mapping')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mapping',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.OntologyTerm'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='trait_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Trait'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trait_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Trait')),
            ],
        ),
        migrations.CreateModel(
            name='MappingSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.OntologyTerm')),
                ('trait_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Trait')),
            ],
            options={
                'unique_together': {('trait_id', 'term_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('trait_id', 'term_id')},
        ),
    ]
