# Generated by Django 3.0.6 on 2020-06-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed', models.BooleanField()),
                ('timestamp_mapped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappingSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=50, null=True)),
                ('uri', models.URLField(null=True)),
                ('label', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('cross_refs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('number_of_source_records', models.IntegerField(null=True)),
                ('timestamp_added', models.DateTimeField(auto_now=True)),
                ('timestamp_updated', models.DateTimeField(auto_now_add=True)),
                ('current_mapping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='mappingsuggestion',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.User'),
        ),
        migrations.AddField(
            model_name='mappingsuggestion',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.OntologyTerm'),
        ),
        migrations.AddField(
            model_name='mappingsuggestion',
            name='trait_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Trait'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.User'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.OntologyTerm'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='trait_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Trait'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='trait_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traits.Trait'),
        ),
    ]
