# Generated by Django 3.0.6 on 2020-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_auto_20200604_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='cross_refs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='curie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='number_of_source_records',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
