# Generated by Django 3.0.6 on 2020-06-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_auto_20200604_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='current_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traits.Mapping'),
        ),
    ]
