# Generated by Django 3.0.7 on 2020-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_auto_20200724_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='is_reviewed',
            field=models.BooleanField(editable=False),
        ),
    ]
