# Generated by Django 3.0.6 on 2020-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_auto_20200609_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='curie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ontologyterm',
            name='uri',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
