# Generated by Django 3.0.6 on 2020-06-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0006_auto_20200614_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('obsolete', 'Obsolete'), ('deleted', 'Deleted'), ('unmapped', 'Unmapped'), ('needs_import', 'Needs Import'), ('awaiting_import', 'Awaiting Import'), ('needs_creation', 'Needs Creation'), ('awaiting_creation', 'Awaiting Creation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trait',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('unmapped', 'Unmapped'), ('obsolete', 'Obsolete'), ('deleted', 'Deleted'), ('awaiting_review', 'Awaiting Review'), ('needs_import', 'Needs Import'), ('awaiting_import', 'Awaiting Import'), ('needs_creation', 'Needs Creation'), ('awaiting_creation', 'Awaiting Creation')], max_length=50),
        ),
    ]
