# Generated by Django 3.0.7 on 2020-08-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0006_review_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='trait_id',
            new_name='mapped_trait',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='term_id',
            new_name='mapped_term',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='trait_id',
            new_name='mapped_trait',
        ),
        migrations.RenameField(
            model_name='mappingsuggestion',
            old_name='term_id',
            new_name='mapped_term',
        ),
        migrations.RenameField(
            model_name='mappingsuggestion',
            old_name='trait_id',
            new_name='mapped_trait',
        ),
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('mapped_trait', 'mapped_term')},
        ),
        migrations.AlterUniqueTogether(
            name='mappingsuggestion',
            unique_together={('mapped_trait', 'mapped_term')},
        ),
    ]
