# Generated by Django 3.0.7 on 2020-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0006_review_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='status',
            field=models.CharField(choices=[('current', 'current'), ('obsolete', 'obsolete'), ('deleted', 'deleted'), ('needs_import', 'needs_import'), ('awaiting_import', 'awaiting_import'), ('needs_creation', 'needs_creation'), ('awaiting_creation', 'awaiting_creation')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trait',
            name='status',
            field=models.CharField(choices=[('current', 'current'), ('unmapped', 'unmapped'), ('obsolete', 'obsolete'), ('deleted', 'deleted'), ('needs_import', 'needs_import'), ('awaiting_import', 'awaiting_import'), ('needs_creation', 'needs_creation'), ('awaiting_creation', 'awaiting_creation'), ('awaiting_review', 'awaiting_review')], editable=False, max_length=30),
        ),
    ]
