# Generated by Django 3.0.7 on 2020-09-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_auto_20200823_1312'),
        ('traits', '0007_auto_20200805_1313'),
    ]

    operations = [
    ]
