# Generated by Django 3.0.6 on 2020-06-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('unmapped', 'Unmapped'), ('obsolete', 'Obsolete'), ('deleted', 'Deleted'), ('needs_import', 'Needs Import'), ('awaiting_import', 'Awaiting Import'), ('needs_creation', 'Needs Creation'), ('awaiting_creation', 'Awaiting Creation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trait',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('unmapped', 'Unmapped'), ('obsolete', 'Obsolete'), ('deleted', 'Deleted'), ('needs_import', 'Needs Import'), ('awaiting_import', 'Awaiting Import'), ('needs_creation', 'Needs Creation'), ('awaiting_creation', 'Awaiting Creation'), ('awaiting_review', 'Awaiting Review')], max_length=50),
        ),
    ]
