# Generated by Django 3.0.7 on 2020-06-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontologyterm',
            old_name='uri',
            new_name='iri',
        ),
    ]
