# Generated by Django 3.0.7 on 2020-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0009_auto_20200619_0809'),
        ('traits', '0009_auto_20200630_0849'),
    ]

    operations = [
    ]
