# Generated by Django 3.0.7 on 2020-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0011_auto_20200701_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('obsolete', 'Obsolete'), ('deleted', 'Deleted'), ('needs_import', 'Needs Import'), ('awaiting_import', 'Awaiting Import'), ('needs_creation', 'Needs Creation'), ('awaiting_creation', 'Awaiting Creation')], max_length=50),
        ),
    ]
