# Generated by Django 3.0.7 on 2020-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0012_auto_20200704_0906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('trait_id', 'term_id')},
        ),
    ]
